#define NO_SYS 0
#define LWIP_DHCP 1
#define LWIP_NETIF_HOSTNAME 1
#define LWIP_DNS 1
#define LWIP_PROVIDE_ERRNO 1
#define LWIP_TIMEVAL_PRIVATE 0
#define portTICK_RATE_MS portTICK_PERIOD_MS

#define TCPIP_THREAD_STACKSIZE 1024
#define DEFAULT_THREAD_STACKSIZE 1024
#define DEFAULT_RAW_RECVMBOX_SIZE 8
#define TCPIP_MBOX_SIZE 8
#define LWIP_TIMEVAL_PRIVATE 0
